# config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm
  mappings:
    book_image:
      uri_prefix: /images/books
      upload_destination: '%kernel.project_dir%/public/images/books'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false